## Project: Unicorn Industry Analysis (2019–2021)

### Business Objective

A unicorn is a privately held company valued at $1 billion or more.

This project looks at companies that became unicorns between 2019 and 2021 to understand which industries produced the most new unicorns.

The analysis focuses on:

- The industries with the highest number of new unicorns
- The number of new unicorns in each year
- The average company valuation across the top three industries

The goal is to compare these industries and understand how the number of new unicorns and their average valuations changed over the three-year period.

### Business Question

Which industries produced the most new unicorns between 2019 and 2021, and how did their yearly unicorn counts and average valuations compare?

---
**Tables Used:**

**`dates`**

  * `company_id` : Unique company identifier
  * `date_joined` : Date the company achieved unicorn status
  * `year_founded` : Year the company was founded

**`industries`**

  * `company_id` : Unique company identifier
  * `industry` : Industry classification

**`funding`**

  * `company_id` : Unique company identifier
  * `valuation` : Company valuation (USD)

**`companies`**

  * `insert columns name` :
  * `inseert column name dont forget!!!` : 
---

In [5]:
SELECT *
FROM industries
LIMIT 5

   company_id                      industry
0         189                        Health
1         848                       Fintech
2         556  Internet software & services
3         999  Internet software & services
4         396                       Fintech

In [6]:
SELECT *
FROM funding
LIMIT 5

   company_id  ...                                   select_investors
0         189  ...                                       EQT Partners
1         848  ...  Dragonfly Captial, Qiming Venture Partners, DS...
2         556  ...              Blackstone, Bessemer Venture Partners
3         999  ...                 Goldman Sachs Asset Management, 3L
4         396  ...  Insight Partners, Softbank Group, Connect Vent...

[5 rows x 4 columns]

In [7]:
SELECT *
FROM dates
LIMIT 5

   company_id               date_joined  year_founded
0         189 2017-06-24 00:00:00+00:00          1919
1         848 2021-06-01 00:00:00+00:00          2019
2         556 2022-02-15 00:00:00+00:00          2011
3         999 2021-11-17 00:00:00+00:00          2020
4         396 2021-10-21 00:00:00+00:00          2021

In [8]:
SELECT *
FROM companies
LIMIT 5

   company_id               company         city        country      continent
0         189  Otto Bock HealthCare   Duderstadt        Germany         Europe
1         848            Matrixport                   Singapore           Asia
2         556            Cloudinary  Santa Clara  United States  North America
3         999                 PLACE   Bellingham  United States  North America
4         396             candy.com     New York  United States  North America

In [9]:
-- Step 1: Identifying the three industries with  
-- the most new unicorns from 2019 through 2021.

WITH top_3 AS (
	SELECT 
		i.industry,
		COUNT(DISTINCT i.company_id) AS total_unicorns
	FROM industries AS i
	INNER JOIN dates AS d
		ON i.company_id = d.company_id
	WHERE d.date_joined >= '2019-01-01'
	  AND D.date_joined < '2022-01-01'
	GROUP BY 
		i.industry
	ORDER BY 
		total_unicorns DESC, 
		i.industry ASC
	LIMIT 3
	),

-- Step 2: Retrieve the companies in those industries
-- and the year each company became a unicorn.
	
unicorn_year AS (
	SELECT
		i.industry,
		i.company_id,
		DATE_PART('year', d.date_joined) AS year
	FROM industries AS i
	INNER JOIN top_3 AS t
		ON i.industry = t.industry
	INNER JOIN dates AS d
		ON d.company_id = i.company_id
	WHERE d.date_joined >= '2019-01-01'
	  AND D.date_joined < '2022-01-01'
	),

-- Step 3: Retrieve the valuation for each company
	
valuations AS (
	SELECT 
		u.*, 
		f.valuation/1000000000.0 AS valuation_billions
	FROM unicorn_year AS u
	LEFT JOIN funding AS f
	ON u.company_id = f.company_id
	)

-- Step 4: Calculating the number of unicorns and
-- average valuation for each industry and year.
	
SELECT 
	industry, 
	year, 
	COUNT(company_id) AS num_unicorns,
	ROUND(AVG(valuation_billions), 2) AS average_valuation_billions
FROM valuations
GROUP BY 
	industry, 
	year
ORDER BY 
	year DESC, 
	num_unicorns DESC,
	industry ASC;

                          industry  ...  average_valuation_billions
0                          Fintech  ...                        2.75
1     Internet software & services  ...                        2.15
2  E-commerce & direct-to-consumer  ...                        2.47
3     Internet software & services  ...                        4.35
4  E-commerce & direct-to-consumer  ...                        4.00
5                          Fintech  ...                        4.33
6                          Fintech  ...                        6.80
7     Internet software & services  ...                        4.23
8  E-commerce & direct-to-consumer  ...                        2.58

[9 rows x 4 columns]

### Key Findings

- **Fintech led the three industries in 2021.** • Fintech produced 138 new unicorns, ahead of Internet Software & Services (119) and E-commerce (47).

- **The number of new unicorns increased substantially in 2021.** All three industries recorded higher counts in 2021 than in 2020, suggesting that unicorn creation surged during the final year of this analysis(2021).

- **Average valuations actually dropped.** Fintech's average valuation decreased from **USD 6.80B** in 2019 to **USD 2.75B** in 2021. Internet software & services decreased from **USD 4.23B** to **USD 2.15B**.

- **More unicorns don't mean higher valuations.** The results show that creating more unicorns doesn't necessarily increase average company valuations; company counts and average value are two entirely different metrics.

---
### Limitations

- **Time period:** This analysis only looks at unicorn companies from 2019 to 2021, so it does not show what happened in later years.
- **Company valuation:** A high company valuation does not always mean the company is making a profit. Some companies may be valued highly because investors expect them to grow in the future, even if they are currently losing money.
- **Average valuation:** The average can be affected by companies with very high valuations, so it may not represent every company in an industry.
- **Data:** The results depend on the accuracy of the information in the datasets, such as company valuations, industries, and the dates they became unicorns.